"""PostgreSQL connection helpers for Voice master file (reporting DB)."""

from __future__ import annotations

import os
import re
import threading
from contextlib import contextmanager
from typing import Any, Iterator, Sequence

import psycopg
from psycopg.rows import dict_row


def _normalize_database_url(raw: str) -> str:
    value = raw.strip()
    if value.startswith("postgresql+psycopg://"):
        value = "postgresql://" + value.removeprefix("postgresql+psycopg://")
    elif value.startswith("postgres+psycopg://"):
        value = "postgresql://" + value.removeprefix("postgres+psycopg://")
    return value


def database_url_from_env() -> str:
    raw = (
        os.getenv("VOICE_DATABASE_URL")
        or os.getenv("DATABASE_URL")
        or ""
    ).strip()
    if not raw:
        raise RuntimeError(
            "VOICE_DATABASE_URL или DATABASE_URL обязателен для Voice "
            "(миграции 050_voice_master.sql и 051_voice_registry.sql)"
        )
    return _normalize_database_url(raw)


_PLACEHOLDER_RE = re.compile(r"(?<!')\?(?!')")
_BEGIN_IMMEDIATE_RE = re.compile(r"^\s*BEGIN\s+IMMEDIATE\s*$", re.IGNORECASE)
_COLLATE_NOCASE_RE = re.compile(r"\s+COLLATE\s+NOCASE", re.IGNORECASE)
_INSERT_OR_IGNORE_RE = re.compile(
    r"INSERT\s+OR\s+IGNORE\s+INTO\s+(\w+)\s*\(([^)]+)\)\s*VALUES\s*\(([^)]+)\)",
    re.IGNORECASE | re.DOTALL,
)
_PRAGMA_RE = re.compile(r"^\s*PRAGMA\b", re.IGNORECASE)
_AUTOINCREMENT_RE = re.compile(
    r"INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT",
    re.IGNORECASE,
)
_JSON_EACH_TWO_RE = re.compile(
    r"(FROM|,)\s*json_each\(([^,]+),\s*'\$\.([A-Za-z0-9_]+)'\)\s+AS\s+(\w+)",
    re.IGNORECASE,
)
_JSON_EACH_ONE_RE = re.compile(
    r"(FROM|,)\s*json_each\(([^)]+)\)\s+AS\s+(\w+)",
    re.IGNORECASE,
)
_TEMP_SCHEMA_RE = re.compile(r"\btemp\.(\w+)", re.IGNORECASE)
# LHS: column or CAST(... AS TEXT) — иначе GLOB съедает слово NOT из NOT GLOB
_GLOB_LHS = r"(?:CAST\([^)]+\s+AS\s+TEXT\)|[A-Za-z_][\w.]*)"
_NOT_GLOB_DIGITS_RE = re.compile(
    rf"({_GLOB_LHS})\s+NOT\s+GLOB\s+'\*\[\^0-9\]\*'",
    re.IGNORECASE,
)
_NOT_GLOB_OP_RE = re.compile(
    rf"({_GLOB_LHS})\s+NOT\s+GLOB\s+(\?|'[^']*')",
    re.IGNORECASE,
)
_GLOB_OP_RE = re.compile(
    rf"({_GLOB_LHS})\s+GLOB\s+(\?|'[^']*')",
    re.IGNORECASE,
)


def translate_sql(sql: str) -> str:
    text = sql.strip()
    if _BEGIN_IMMEDIATE_RE.match(text):
        return "BEGIN"
    if _PRAGMA_RE.match(text):
        return "SELECT 1"
    text = _COLLATE_NOCASE_RE.sub("", text)
    text = _AUTOINCREMENT_RE.sub(
        "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        text,
    )
    # «только цифры» → master_is_digits (как в MASTER_SHORT_AON_SQL)
    text = _NOT_GLOB_DIGITS_RE.sub(r"master_is_digits(\1)", text)
    text = _NOT_GLOB_OP_RE.sub(r"(NOT master_glob_match(\1, \2))", text)
    text = _GLOB_OP_RE.sub(r"master_glob_match(\1, \2)", text)
    text = _JSON_EACH_TWO_RE.sub(
        r"\1 jsonb_array_elements_text(((\2)::jsonb)->'\3') AS \4(value)",
        text,
    )
    text = _JSON_EACH_ONE_RE.sub(
        r"\1 jsonb_array_elements_text((\2)::jsonb) AS \3(value)",
        text,
    )
    text = _TEMP_SCHEMA_RE.sub(r"\1", text)

    def _insert_or_ignore(match: re.Match[str]) -> str:
        table = match.group(1)
        cols = match.group(2)
        vals = match.group(3)
        return (
            f"INSERT INTO {table} ({cols}) VALUES ({vals}) "
            f"ON CONFLICT DO NOTHING"
        )

    text = _INSERT_OR_IGNORE_RE.sub(_insert_or_ignore, text)
    text = text.replace("WITHOUT ROWID", "")
    text = _PLACEHOLDER_RE.sub("%s", text)
    return text


def _split_script(script: str) -> list[str]:
    parts: list[str] = []
    buf: list[str] = []
    in_single = False
    i = 0
    while i < len(script):
        ch = script[i]
        if ch == "'" and not in_single:
            in_single = True
            buf.append(ch)
        elif ch == "'" and in_single:
            buf.append(ch)
            if i + 1 < len(script) and script[i + 1] == "'":
                buf.append("'")
                i += 1
            else:
                in_single = False
        elif ch == ";" and not in_single:
            statement = "".join(buf).strip()
            if statement:
                parts.append(statement)
            buf = []
        else:
            buf.append(ch)
        i += 1
    tail = "".join(buf).strip()
    if tail:
        parts.append(tail)
    return parts


class PgRow(dict):
    """dict-like row that also supports integer and attribute access."""

    def __getitem__(self, key: Any) -> Any:
        if isinstance(key, int):
            return list(self.values())[key]
        return super().__getitem__(key)

    def __getattr__(self, item: str) -> Any:
        try:
            return self[item]
        except KeyError as exc:
            raise AttributeError(item) from exc


class PgCursor:
    def __init__(self, cursor: psycopg.Cursor):
        self._cursor = cursor
        self.lastrowid: Any = None
        self.rowcount = 0

    def execute(self, sql: str, params: Sequence[Any] | None = None) -> "PgCursor":
        translated = translate_sql(sql)
        if translated == "SELECT 1" and _PRAGMA_RE.match(sql.strip()):
            self._cursor.execute("SELECT 1")
            self.rowcount = 0
            return self
        if params is None:
            self._cursor.execute(translated)
        else:
            self._cursor.execute(translated, tuple(params))
        self.rowcount = self._cursor.rowcount
        return self

    def executemany(self, sql: str, seq_of_params: Sequence[Sequence[Any]]) -> "PgCursor":
        translated = translate_sql(sql)
        self._cursor.executemany(translated, [tuple(p) for p in seq_of_params])
        self.rowcount = self._cursor.rowcount
        return self

    def fetchone(self) -> PgRow | None:
        row = self._cursor.fetchone()
        if row is None:
            return None
        if isinstance(row, dict):
            return PgRow(row)
        columns = [col.name for col in self._cursor.description or []]
        return PgRow(dict(zip(columns, row)))

    def fetchall(self) -> list[PgRow]:
        rows = self._cursor.fetchall()
        result: list[PgRow] = []
        for row in rows:
            if isinstance(row, dict):
                result.append(PgRow(row))
            else:
                columns = [col.name for col in self._cursor.description or []]
                result.append(PgRow(dict(zip(columns, row))))
        return result

    def fetchmany(self, size: int | None = None) -> list[PgRow]:
        rows = self._cursor.fetchmany(size if size is not None else self._cursor.arraysize)
        result: list[PgRow] = []
        for row in rows:
            if isinstance(row, dict):
                result.append(PgRow(row))
            else:
                columns = [col.name for col in self._cursor.description or []]
                result.append(PgRow(dict(zip(columns, row))))
        return result

    def close(self) -> None:
        self._cursor.close()

    def __iter__(self) -> Iterator[PgRow]:
        while True:
            row = self.fetchone()
            if row is None:
                break
            yield row


class PgConnection:
    """sqlite3-like facade over psycopg for MasterService."""

    def __init__(self, conn: psycopg.Connection):
        self._conn = conn
        self._in_transaction = False

    def execute(self, sql: str, params: Sequence[Any] | None = None) -> PgCursor:
        cur = PgCursor(self._conn.cursor(row_factory=dict_row))
        statement = sql.strip()
        if _BEGIN_IMMEDIATE_RE.match(statement) or statement.upper() == "BEGIN":
            if not self._in_transaction:
                self._conn.execute("BEGIN")
                self._in_transaction = True
            return cur
        upper = statement.upper()
        if upper in {"COMMIT", "ROLLBACK"}:
            self._conn.execute(upper)
            self._in_transaction = False
            return cur
        cur.execute(sql, params)
        return cur

    def executemany(self, sql: str, seq_of_params: Sequence[Sequence[Any]]) -> PgCursor:
        cur = PgCursor(self._conn.cursor(row_factory=dict_row))
        cur.executemany(sql, seq_of_params)
        return cur

    def executescript(self, script: str) -> None:
        for statement in _split_script(script):
            upper = statement.upper()
            # Permanent schema + SQLite triggers come from reporting migrations.
            if "CREATE TRIGGER" in upper or "DROP TRIGGER" in upper:
                continue
            if re.match(
                r"CREATE\s+TABLE\s+(IF\s+NOT\s+EXISTS\s+)?master_",
                statement,
                re.IGNORECASE,
            ):
                continue
            if re.match(
                r"ALTER\s+TABLE\s+master_records\s+RENAME",
                statement,
                re.IGNORECASE,
            ):
                continue
            if re.match(r"DROP\s+TABLE\s+master_records_unique", statement, re.I):
                continue
            if re.match(
                r"CREATE\s+INDEX\s+(IF\s+NOT\s+EXISTS\s+)?master_",
                statement,
                re.IGNORECASE,
            ):
                continue
            if re.match(
                r"CREATE\s+TABLE\s+(IF\s+NOT\s+EXISTS\s+)?voice_",
                statement,
                re.IGNORECASE,
            ):
                continue
            if re.match(
                r"CREATE\s+INDEX\s+(IF\s+NOT\s+EXISTS\s+)?voice_",
                statement,
                re.IGNORECASE,
            ):
                continue
            self.execute(statement)

    def commit(self) -> None:
        self._conn.commit()
        self._in_transaction = False

    def rollback(self) -> None:
        self._conn.rollback()
        self._in_transaction = False

    def close(self) -> None:
        if not self._conn.closed:
            self._conn.close()

    def create_function(self, *args: Any, **kwargs: Any) -> None:
        return

    def __enter__(self) -> "PgConnection":
        return self

    def __exit__(self, exc_type, exc, tb) -> None:
        try:
            if exc_type is None:
                self.commit()
            else:
                self.rollback()
        finally:
            self.close()


_pool_lock = threading.Lock()
_conninfo: str | None = None


def configure(database_url: str | None = None) -> None:
    global _conninfo
    with _pool_lock:
        _conninfo = _normalize_database_url(database_url or database_url_from_env())


def connect() -> PgConnection:
    global _conninfo
    if not _conninfo:
        configure()
    assert _conninfo is not None
    raw = psycopg.connect(_conninfo, autocommit=False)
    return PgConnection(raw)


@contextmanager
def connection() -> Iterator[PgConnection]:
    conn = connect()
    try:
        yield conn
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()
